// Centralized dummy data for the entire dashboard

// User Management Data
export const dummyUsers = [
    {
        id: "USR001",
        name: "Sarah Johnson",
        email: "sarah.johnson@email.com",
        phone: "+1 (555) 123-4567",
        registrationDate: "2024-01-15",
        status: "Active",
        baselineData: {
            age: 34,
            gender: "Female",
            height: "165 cm",
            weight: "62 kg",
            bloodType: "A+",
            chronicConditions: ["Chronic Back Pain", "Mild Anxiety"],
            medications: ["Ibuprofen 400mg", "Vitamin D3"],
        },
        phenotype: {
            painSensitivity: "High",
            stressResponse: "Moderate",
            sleepQuality: "Poor",
            physicalActivity: "Sedentary",
            dietQuality: "Good",
            cognitiveFunction: "Above Average",
        },
        progress: {
            painLevelTrend: [7, 6.5, 6, 5.5, 5, 4.5, 4],
            moodScores: [5, 5.5, 6, 6.5, 7, 7.5, 8],
            exerciseMinutes: [0, 10, 15, 20, 25, 30, 35],
            sleepHours: [5.5, 6, 6, 6.5, 7, 7, 7.5],
            dates: ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5", "Week 6", "Week 7"],
        },
    },
    {
        id: "USR002",
        name: "Michael Chen",
        email: "michael.chen@email.com",
        phone: "+1 (555) 234-5678",
        registrationDate: "2024-02-03",
        status: "Active",
        baselineData: {
            age: 45,
            gender: "Male",
            height: "178 cm",
            weight: "82 kg",
            bloodType: "O+",
            chronicConditions: ["Type 2 Diabetes", "Hypertension"],
            medications: ["Metformin 500mg", "Lisinopril 10mg"],
        },
        phenotype: {
            painSensitivity: "Moderate",
            stressResponse: "High",
            sleepQuality: "Fair",
            physicalActivity: "Moderate",
            dietQuality: "Fair",
            cognitiveFunction: "Average",
        },
        progress: {
            painLevelTrend: [5, 4.8, 4.5, 4.2, 4, 3.8, 3.5],
            moodScores: [6, 6.2, 6.5, 6.8, 7, 7.2, 7.5],
            exerciseMinutes: [15, 20, 25, 30, 35, 40, 45],
            sleepHours: [6, 6.5, 6.5, 7, 7, 7.5, 7.5],
            dates: ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5", "Week 6", "Week 7"],
        },
    },
    {
        id: "USR003",
        name: "Emily Rodriguez",
        email: "emily.rodriguez@email.com",
        phone: "+1 (555) 345-6789",
        registrationDate: "2023-11-20",
        status: "Active",
        baselineData: {
            age: 29,
            gender: "Female",
            height: "160 cm",
            weight: "58 kg",
            bloodType: "B+",
            chronicConditions: ["Fibromyalgia", "Depression"],
            medications: ["Duloxetine 60mg", "Pregabalin 75mg"],
        },
        phenotype: {
            painSensitivity: "Very High",
            stressResponse: "Very High",
            sleepQuality: "Very Poor",
            physicalActivity: "Low",
            dietQuality: "Excellent",
            cognitiveFunction: "High",
        },
        progress: {
            painLevelTrend: [8, 7.8, 7.5, 7, 6.8, 6.5, 6.2],
            moodScores: [4, 4.5, 5, 5.5, 6, 6.5, 7],
            exerciseMinutes: [0, 5, 10, 15, 20, 25, 30],
            sleepHours: [4.5, 5, 5.5, 6, 6, 6.5, 6.5],
            dates: ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5", "Week 6", "Week 7"],
        },
    },
    {
        id: "USR004",
        name: "David Thompson",
        email: "david.thompson@email.com",
        phone: "+1 (555) 456-7890",
        registrationDate: "2024-03-10",
        status: "Inactive",
        baselineData: {
            age: 52,
            gender: "Male",
            height: "182 cm",
            weight: "95 kg",
            bloodType: "AB+",
            chronicConditions: ["Osteoarthritis", "Sleep Apnea"],
            medications: ["Naproxen 500mg", "CPAP therapy"],
        },
        phenotype: {
            painSensitivity: "High",
            stressResponse: "Low",
            sleepQuality: "Poor",
            physicalActivity: "Low",
            dietQuality: "Poor",
            cognitiveFunction: "Average",
        },
        progress: {
            painLevelTrend: [6, 6, 5.8, 5.5, 5.5, 5.2, 5],
            moodScores: [5.5, 5.8, 6, 6, 6.2, 6.5, 6.5],
            exerciseMinutes: [5, 10, 10, 15, 15, 20, 20],
            sleepHours: [5, 5.5, 5.5, 6, 6, 6.5, 6.5],
            dates: ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5", "Week 6", "Week 7"],
        },
    },
    {
        id: "USR005",
        name: "Lisa Anderson",
        email: "lisa.anderson@email.com",
        phone: "+1 (555) 567-8901",
        registrationDate: "2024-01-28",
        status: "Active",
        baselineData: {
            age: 38,
            gender: "Female",
            height: "170 cm",
            weight: "68 kg",
            bloodType: "O-",
            chronicConditions: ["Migraine", "IBS"],
            medications: ["Sumatriptan 50mg", "Probiotics"],
        },
        phenotype: {
            painSensitivity: "High",
            stressResponse: "High",
            sleepQuality: "Fair",
            physicalActivity: "Moderate",
            dietQuality: "Good",
            cognitiveFunction: "High",
        },
        progress: {
            painLevelTrend: [7.5, 7, 6.5, 6, 5.5, 5, 4.5],
            moodScores: [5.5, 6, 6.5, 7, 7.5, 8, 8.5],
            exerciseMinutes: [10, 15, 20, 25, 30, 35, 40],
            sleepHours: [6, 6.5, 6.5, 7, 7, 7.5, 8],
            dates: ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5", "Week 6", "Week 7"],
        },
    },
];

// Questionnaire & Assessment Data
export const questionnaireResponses = [
    {
        id: "QR001",
        userId: "USR001",
        userName: "Sarah Johnson",
        questionnaireName: "Pain Assessment Scale",
        domain: "Biological",
        date: "2024-12-20",
        status: "Complete",
        score: 65,
        responses: {
            q1: "Pain level: 6/10",
            q2: "Location: Lower back",
            q3: "Duration: 3 months",
            q4: "Triggers: Sitting for long periods",
            q5: "Relief factors: Heat therapy, stretching",
        },
    },
    {
        id: "QR002",
        userId: "USR002",
        userName: "Michael Chen",
        questionnaireName: "Stress & Anxiety Inventory",
        domain: "Psychological",
        date: "2024-12-19",
        status: "Complete",
        score: 72,
        responses: {
            q1: "Stress level: 7/10",
            q2: "Main stressors: Work deadlines, family",
            q3: "Coping mechanisms: Exercise, meditation",
            q4: "Sleep affected: Yes, occasionally",
            q5: "Professional support: Considering therapy",
        },
    },
    {
        id: "QR003",
        userId: "USR003",
        userName: "Emily Rodriguez",
        questionnaireName: "Social Support Assessment",
        domain: "Social",
        date: "2024-12-18",
        status: "Incomplete",
        score: 45,
        responses: {
            q1: "Support network: Small but close",
            q2: "Family involvement: Moderate",
            q3: "Social activities: 1-2 per month",
            q4: "Isolation feelings: Sometimes",
            q5: "Not answered",
        },
    },
    {
        id: "QR004",
        userId: "USR001",
        userName: "Sarah Johnson",
        questionnaireName: "Cognitive Function Test",
        domain: "Psychological",
        date: "2024-12-15",
        status: "Complete",
        score: 88,
        responses: {
            q1: "Memory recall: Excellent",
            q2: "Concentration: Good",
            q3: "Problem solving: Above average",
            q4: "Processing speed: Fast",
            q5: "Mental clarity: High",
        },
    },
    {
        id: "QR005",
        userId: "USR004",
        userName: "David Thompson",
        questionnaireName: "Physical Activity Readiness",
        domain: "Biological",
        date: "2024-12-14",
        status: "Complete",
        score: 58,
        responses: {
            q1: "Current activity level: Low",
            q2: "Physical limitations: Joint pain",
            q3: "Exercise history: Sporadic",
            q4: "Medical clearance: Yes",
            q5: "Goals: Improve mobility, reduce pain",
        },
    },
    {
        id: "QR006",
        userId: "USR005",
        userName: "Lisa Anderson",
        questionnaireName: "Sleep Quality Index",
        domain: "Biological",
        date: "2024-12-12",
        status: "Incomplete",
        score: 52,
        responses: {
            q1: "Hours per night: 6-7",
            q2: "Sleep interruptions: 2-3 times",
            q3: "Morning energy: Low to moderate",
            q4: "Not answered",
            q5: "Not answered",
        },
    },
];

// Content Management Data
export const physicalExercises = [
    {
        id: "EX001",
        title: "Lower Back Stretching Routine",
        description: "Gentle stretches to relieve lower back tension and improve flexibility",
        duration: "15 minutes",
        difficulty: "Beginner",
        videoUrl: "https://example.com/videos/back-stretch.mp4",
        thumbnailUrl: "https://via.placeholder.com/400x225/4F46E5/FFFFFF?text=Back+Stretching",
        category: "Stretching",
        targetArea: "Lower Back",
        equipment: "Yoga mat",
        views: 1247,
        createdDate: "2024-11-05",
    },
    {
        id: "EX002",
        title: "Core Strengthening for Pain Relief",
        description: "Build core stability to support your spine and reduce pain",
        duration: "20 minutes",
        difficulty: "Intermediate",
        videoUrl: "https://example.com/videos/core-strength.mp4",
        thumbnailUrl: "https://via.placeholder.com/400x225/7C3AED/FFFFFF?text=Core+Strength",
        category: "Strength",
        targetArea: "Core",
        equipment: "None",
        views: 892,
        createdDate: "2024-11-10",
    },
    {
        id: "EX003",
        title: "Gentle Neck Mobility Exercises",
        description: "Reduce neck tension and improve range of motion",
        duration: "10 minutes",
        difficulty: "Beginner",
        videoUrl: "https://example.com/videos/neck-mobility.mp4",
        thumbnailUrl: "https://via.placeholder.com/400x225/EC4899/FFFFFF?text=Neck+Mobility",
        category: "Mobility",
        targetArea: "Neck & Shoulders",
        equipment: "None",
        views: 1523,
        createdDate: "2024-11-15",
    },
    {
        id: "EX004",
        title: "Mindful Walking Practice",
        description: "Low-impact cardio combined with mindfulness for pain management",
        duration: "30 minutes",
        difficulty: "Beginner",
        videoUrl: "https://example.com/videos/mindful-walking.mp4",
        thumbnailUrl: "https://via.placeholder.com/400x225/10B981/FFFFFF?text=Mindful+Walking",
        category: "Cardio",
        targetArea: "Full Body",
        equipment: "Comfortable shoes",
        views: 2041,
        createdDate: "2024-11-20",
    },
];

export const cognitiveTraining = [
    {
        id: "COG001",
        title: "Memory Enhancement Module",
        description: "Interactive exercises to improve short-term and working memory",
        duration: "15 minutes",
        difficulty: "Beginner",
        apiStatus: "Connected",
        lastSync: "2024-12-23 10:30 AM",
        completionRate: 78,
        averageScore: 82,
        sessions: 456,
        category: "Memory",
    },
    {
        id: "COG002",
        title: "Attention & Focus Training",
        description: "Games designed to enhance sustained attention and concentration",
        duration: "20 minutes",
        difficulty: "Intermediate",
        apiStatus: "Connected",
        lastSync: "2024-12-23 11:15 AM",
        completionRate: 65,
        averageScore: 75,
        sessions: 332,
        category: "Attention",
    },
    {
        id: "COG003",
        title: "Problem-Solving Challenges",
        description: "Logic puzzles and scenarios to boost analytical thinking",
        duration: "25 minutes",
        difficulty: "Advanced",
        apiStatus: "Syncing...",
        lastSync: "2024-12-23 09:00 AM",
        completionRate: 52,
        averageScore: 68,
        sessions: 198,
        category: "Logic",
    },
    {
        id: "COG004",
        title: "Processing Speed Drills",
        description: "Rapid response exercises to improve mental processing speed",
        duration: "10 minutes",
        difficulty: "Beginner",
        apiStatus: "Connected",
        lastSync: "2024-12-23 11:45 AM",
        completionRate: 84,
        averageScore: 88,
        sessions: 612,
        category: "Speed",
    },
];

export const educationalModules = [
    {
        id: "EDU001",
        title: "Understanding Chronic Pain",
        description: "Comprehensive overview of chronic pain mechanisms and management strategies",
        type: "Lesson",
        duration: "30 minutes",
        imageUrl: "https://via.placeholder.com/600x400/F59E0B/FFFFFF?text=Chronic+Pain",
        content: "Detailed lesson content about pain science...",
        completed: 234,
        rating: 4.7,
        category: "Pain Science",
        createdDate: "2024-10-15",
    },
    {
        id: "EDU002",
        title: "Stress Management Techniques",
        description: "Learn evidence-based methods to reduce and manage stress",
        type: "Video",
        duration: "45 minutes",
        imageUrl: "https://via.placeholder.com/600x400/3B82F6/FFFFFF?text=Stress+Management",
        videoUrl: "https://example.com/videos/stress-management.mp4",
        completed: 412,
        rating: 4.9,
        category: "Mental Health",
        createdDate: "2024-10-22",
    },
    {
        id: "EDU003",
        title: "Nutrition for Pain Relief",
        description: "How diet and nutrition impact pain levels and overall health",
        type: "Lesson",
        duration: "25 minutes",
        imageUrl: "https://via.placeholder.com/600x400/10B981/FFFFFF?text=Nutrition",
        content: "Detailed lesson about anti-inflammatory foods...",
        completed: 189,
        rating: 4.5,
        category: "Nutrition",
        createdDate: "2024-11-01",
    },
    {
        id: "EDU004",
        title: "Sleep Hygiene Masterclass",
        description: "Practical strategies to improve sleep quality and duration",
        type: "Video",
        duration: "35 minutes",
        imageUrl: "https://via.placeholder.com/600x400/8B5CF6/FFFFFF?text=Sleep+Hygiene",
        videoUrl: "https://example.com/videos/sleep-hygiene.mp4",
        completed: 356,
        rating: 4.8,
        category: "Sleep",
        createdDate: "2024-11-10",
    },
];

// Notification Data
export const notificationTemplates = [
    {
        id: "TPL001",
        name: "Daily Check-in Reminder",
        message: "Don't forget to log your pain level and mood today!",
        type: "Reminder",
        frequency: "Daily",
        time: "09:00 AM",
    },
    {
        id: "TPL002",
        name: "Exercise Streak Celebration",
        message: "Amazing! You're on a {streak_days}-day exercise streak! Keep it up!",
        type: "Motivation",
        frequency: "On Achievement",
        trigger: "Exercise Streak",
    },
    {
        id: "TPL003",
        name: "Questionnaire Follow-up",
        message: "You have an incomplete questionnaire. Complete it to track your progress!",
        type: "Alert",
        frequency: "Weekly",
        time: "06:00 PM",
    },
    {
        id: "TPL004",
        name: "Bedtime Relaxation",
        message: "Wind down with a guided meditation to improve your sleep quality.",
        type: "Reminder",
        frequency: "Daily",
        time: "09:30 PM",
    },
];

export const notificationHistory = [
    {
        id: "NOT001",
        userId: "USR001",
        userName: "Sarah Johnson",
        message: "Don't forget to log your pain level and mood today!",
        type: "Reminder",
        status: "Delivered",
        sentDate: "2024-12-23 09:00 AM",
        readDate: "2024-12-23 09:15 AM",
    },
    {
        id: "NOT002",
        userId: "USR002",
        userName: "Michael Chen",
        message: "Amazing! You're on a 7-day exercise streak! Keep it up!",
        type: "Motivation",
        status: "Delivered",
        sentDate: "2024-12-23 08:30 AM",
        readDate: "2024-12-23 08:45 AM",
    },
    {
        id: "NOT003",
        userId: "USR003",
        userName: "Emily Rodriguez",
        message: "You have an incomplete questionnaire. Complete it to track your progress!",
        type: "Alert",
        status: "Delivered",
        sentDate: "2024-12-22 06:00 PM",
        readDate: null,
    },
    {
        id: "NOT004",
        userId: "USR005",
        userName: "Lisa Anderson",
        message: "Wind down with a guided meditation to improve your sleep quality.",
        type: "Reminder",
        status: "Pending",
        sentDate: "2024-12-23 09:30 PM",
        readDate: null,
    },
];

// Analytics Data
export const analyticsData = {
    globalUsageStats: {
        totalUsers: 5432,
        activeUsers: 3876,
        totalSessions: 45678,
        averageSessionDuration: "24 minutes",
        totalExercisesCompleted: 12456,
        totalAssessmentsCompleted: 8934,
        userGrowth: "+12.5%",
        engagement: "71.3%",
    },
    painTrends: {
        labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        data: [6.5, 6.3, 6.1, 5.9, 5.7, 5.5, 5.3, 5.1, 4.9, 4.7, 4.5, 4.3],
        title: "Average Pain Level Over Time",
    },
    cognitivePerformance: {
        labels: ["Memory", "Attention", "Logic", "Speed", "Flexibility"],
        data: [82, 75, 68, 88, 71],
        title: "Cognitive Performance Scores",
    },
    exerciseMoodSleep: {
        labels: ["Week 1", "Week 2", "Week 3", "Week 4", "Week 5", "Week 6", "Week 7", "Week 8"],
        exercise: [120, 145, 168, 189, 210, 235, 258, 280],
        mood: [5.5, 5.8, 6.1, 6.4, 6.7, 7.0, 7.3, 7.6],
        sleep: [5.8, 6.0, 6.2, 6.5, 6.7, 7.0, 7.2, 7.5],
        title: "Exercise, Mood & Sleep Evolution",
    },
    userEngagement: {
        labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        data: [425, 478, 512, 489, 523, 398, 356],
        title: "Daily Active Users",
    },
};

// Admin & Security Data
export const adminRoles = [
    {
        id: "ROLE001",
        name: "Super Admin",
        description: "Full system access with all permissions",
        permissions: ["read", "write", "delete", "manage_users", "manage_roles", "system_settings", "export_data"],
        userCount: 2,
    },
    {
        id: "ROLE002",
        name: "Admin",
        description: "Standard admin with most permissions",
        permissions: ["read", "write", "delete", "export_data"],
        userCount: 5,
    },
    {
        id: "ROLE003",
        name: "Researcher",
        description: "Read access with export capabilities",
        permissions: ["read", "export_data"],
        userCount: 12,
    },
    {
        id: "ROLE004",
        name: "Read-only",
        description: "View-only access without modifications",
        permissions: ["read"],
        userCount: 8,
    },
];

export const adminUsers = [
    {
        id: "ADM001",
        name: "Dr. Jennifer Williams",
        email: "j.williams@beiadmin.com",
        role: "Super Admin",
        lastLogin: "2024-12-23 11:30 AM",
        status: "Active",
        twoFactorEnabled: true,
    },
    {
        id: "ADM002",
        name: "Dr. Robert Martinez",
        email: "r.martinez@beiadmin.com",
        role: "Admin",
        lastLogin: "2024-12-23 10:15 AM",
        status: "Active",
        twoFactorEnabled: true,
    },
    {
        id: "ADM003",
        name: "Dr. Patricia Lee",
        email: "p.lee@beiadmin.com",
        role: "Researcher",
        lastLogin: "2024-12-22 03:45 PM",
        status: "Active",
        twoFactorEnabled: false,
    },
    {
        id: "ADM004",
        name: "John Davis",
        email: "j.davis@beiadmin.com",
        role: "Read-only",
        lastLogin: "2024-12-20 09:00 AM",
        status: "Active",
        twoFactorEnabled: false,
    },
];

export const adminLogs = [
    {
        id: "LOG001",
        adminId: "ADM001",
        adminName: "Dr. Jennifer Williams",
        action: "Created new user account",
        target: "USR006 - Mark Wilson",
        timestamp: "2024-12-23 11:15 AM",
        ipAddress: "192.168.1.105",
        status: "Success",
    },
    {
        id: "LOG002",
        adminId: "ADM002",
        adminName: "Dr. Robert Martinez",
        action: "Updated exercise content",
        target: "EX002 - Core Strengthening",
        timestamp: "2024-12-23 10:30 AM",
        ipAddress: "192.168.1.112",
        status: "Success",
    },
    {
        id: "LOG003",
        adminId: "ADM001",
        adminName: "Dr. Jennifer Williams",
        action: "Exported user data",
        target: "All active users (CSV)",
        timestamp: "2024-12-23 09:45 AM",
        ipAddress: "192.168.1.105",
        status: "Success",
    },
    {
        id: "LOG004",
        adminId: "ADM003",
        adminName: "Dr. Patricia Lee",
        action: "Attempted role modification",
        target: "ADM004 - John Davis",
        timestamp: "2024-12-22 04:00 PM",
        ipAddress: "192.168.1.128",
        status: "Failed - Insufficient permissions",
    },
    {
        id: "LOG005",
        adminId: "ADM002",
        adminName: "Dr. Robert Martinez",
        action: "Sent push notification",
        target: "All active users",
        timestamp: "2024-12-22 09:00 AM",
        ipAddress: "192.168.1.112",
        status: "Success",
    },
];

// System Settings Data
export const systemSettings = {
    language: {
        current: "en-US",
        available: [
            { code: "en-US", name: "English (US)" },
            { code: "es-ES", name: "Spanish (Spain)" },
            { code: "fr-FR", name: "French (France)" },
            { code: "de-DE", name: "German (Germany)" },
            { code: "zh-CN", name: "Chinese (Simplified)" },
        ],
    },
    apiKeys: [
        {
            id: "API001",
            name: "Cognitive Training API",
            key: "ct_live_4Rf8n2K9mP3xQ7sT1vW6",
            status: "Active",
            createdDate: "2024-01-15",
            lastUsed: "2024-12-23 11:45 AM",
            requestsToday: 1247,
        },
        {
            id: "API002",
            name: "Push Notification Service",
            key: "pns_live_9Xy2L4bV7nH1pW8jK3mR",
            status: "Active",
            createdDate: "2024-02-03",
            lastUsed: "2024-12-23 09:30 AM",
            requestsToday: 456,
        },
        {
            id: "API003",
            name: "Analytics Platform",
            key: "ap_live_5Qw8T2nM6kB9xC4vZ7yL",
            status: "Active",
            createdDate: "2024-03-10",
            lastUsed: "2024-12-23 12:00 PM",
            requestsToday: 89,
        },
        {
            id: "API004",
            name: "Video Storage CDN",
            key: "vsc_live_3Hj7P1qF4xN8bM2sV5tW",
            status: "Inactive",
            createdDate: "2024-11-05",
            lastUsed: "2024-12-15 02:30 PM",
            requestsToday: 0,
        },
    ],
    backupSchedule: {
        frequency: "Daily",
        time: "02:00 AM",
        lastBackup: "2024-12-23 02:00 AM",
        nextBackup: "2024-12-24 02:00 AM",
        status: "Completed",
        retentionDays: 30,
        location: "AWS S3 - us-east-1",
    },
    systemPreferences: {
        maintenanceMode: false,
        debugMode: false,
        emailNotifications: true,
        autoBackup: true,
        sessionTimeout: 30,
        maxLoginAttempts: 5,
    },
};
